# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(610, 556)
        self.browseButton = QtWidgets.QPushButton(MainWindow)
        self.browseButton.setGeometry(QtCore.QRect(20, 20, 171, 31))
        self.browseButton.setObjectName("browseButton")
        self.versionLabel = QtWidgets.QLabel(MainWindow)
        self.versionLabel.setGeometry(QtCore.QRect(210, 20, 141, 31))
        self.versionLabel.setObjectName("versionLabel")
        self.versionList = QtWidgets.QListWidget(MainWindow)
        self.versionList.setGeometry(QtCore.QRect(400, 40, 191, 231))
        self.versionList.setObjectName("versionList")
        self.upgradeButton = QtWidgets.QPushButton(MainWindow)
        self.upgradeButton.setGeometry(QtCore.QRect(100, 80, 201, 31))
        self.upgradeButton.setObjectName("upgradeButton")
        self.downgradeButton = QtWidgets.QPushButton(MainWindow)
        self.downgradeButton.setGeometry(QtCore.QRect(100, 130, 201, 31))
        self.downgradeButton.setObjectName("downgradeButton")
        self.steamUsername = QtWidgets.QLineEdit(MainWindow)
        self.steamUsername.setGeometry(QtCore.QRect(170, 190, 113, 31))
        self.steamUsername.setText("")
        self.steamUsername.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.steamUsername.setObjectName("steamUsername")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(20, 190, 111, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.steamPassword = QtWidgets.QLineEdit(MainWindow)
        self.steamPassword.setGeometry(QtCore.QRect(170, 240, 113, 31))
        self.steamPassword.setText("")
        self.steamPassword.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.steamPassword.setObjectName("steamPassword")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(20, 240, 111, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.performOperation = QtWidgets.QPushButton(MainWindow)
        self.performOperation.setGeometry(QtCore.QRect(130, 490, 291, 41))
        self.performOperation.setObjectName("performOperation")
        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setGeometry(QtCore.QRect(20, 390, 561, 31))
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.uhdCheckbox = QtWidgets.QCheckBox(MainWindow)
        self.uhdCheckbox.setGeometry(QtCore.QRect(20, 440, 281, 17))
        self.uhdCheckbox.setObjectName("uhdCheckbox")
        self.versionLabel_2 = QtWidgets.QLabel(MainWindow)
        self.versionLabel_2.setGeometry(QtCore.QRect(410, 10, 171, 21))
        self.versionLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.versionLabel_2.setObjectName("versionLabel_2")
        self.label_4 = QtWidgets.QLabel(MainWindow)
        self.label_4.setGeometry(QtCore.QRect(20, 290, 561, 81))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Test"))
        self.browseButton.setText(_translate("MainWindow", "Browse for AoE2DE_s.exe"))
        self.versionLabel.setText(_translate("MainWindow", "Current Version: "))
        self.upgradeButton.setText(_translate("MainWindow", "Upgrade to"))
        self.downgradeButton.setText(_translate("MainWindow", "Downgrade to"))
        self.label.setText(_translate("MainWindow", "Steam Username"))
        self.label_2.setText(_translate("MainWindow", "Steam Password"))
        self.performOperation.setText(_translate("MainWindow", "Start"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Your Steam credentials are only used to download the files from Steam. This program is open-source and you can have a look at it here: <a href=\" https://cyanide-aoe2.github.io/downgrader\"><span style=\" text-decoration: underline; color:#0000ff;\">https://cyanide-aoe2.github.io/downgrader</span></a></p></body></html>"))
        self.uhdCheckbox.setText(_translate("MainWindow", "Include UHD/4K assets when downgrading/upgrading"))
        self.versionLabel_2.setText(_translate("MainWindow", "Available Versions"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Original files will be backed up automatically.</p><p>The downgrade/upgrade operation cannot jump versions currently. To go down by more than 1 version (eg: from 39515 to 37906), you need to go through each version. This is to ensure that the correct file versions are present. Future updates will allow jumping multiple versions in a single step.</p></body></html>"))
